Konzept
=======

= Kurz Erklärt

Es gibt eine Vielzahl von Erweiterungskomponenten und Sensoren für Raspberry PI - wie z.B. Temperatursensoren, Relaiskarten, Bewegungssensoren. Damit lassen sich kostengünstig verschiedenste Homeautomation Anwendungen bauen. Wenn du schon einmal versucht hast solch ein Projekt umzusetzen, stösst jeder früher oder später auf die gleichen Probleme:

    * Welche Hardware brauche ich (PI-Version, SD-Karten-Größe)
    * Wie muss ich die Erweiterungskarte an den PI anschliessen?
    * Welche Software brauche ich um die Karte anzuprogrammieren?
    * Wie geht nochmal Python?
    * Wie kann ich die Ergebnisse anzeigen (WebUI, App...)
    * Wie startet mein Script automatisch?
    * usw...

Das Ziel von jum: ist es, die Benutzung von Raspberry PI Erweiterungskomponenten einfach zu gestalten und es zu Ermöglichen in einigen wenigen einfachen Schritten, angefangen von der Hardware-Zusammenstellung zu einem fertigen einsatzbereiten Sensor zu kommen.

jum:templates stellt hierbei die Software und eine einfache Beschreibung für viele gängigen Komponenten zur Verfügung. 

Wenn du es dann geschafft hats, dein Raspberry PI Projekt umzusetzen, stellst du dir sicher schnell die Frage, wie die Sensor-Daten nun mit bestehenden Homeautomation-Lösungen (Philips Hue, Google Home, Homematic, Staubsaugerroboter usw.) kombiniert werden können. Zum einen möchstest du möglicherweise alle eingesetzen Lösungen in einer App sehen und steuern können. Zum anderen möchtest du vielleicht Regeln definieren können die deine Raspberry PI Sensoren und Aktoren mit anderen Systemen kombinieren. 

jum:projects liefert dir Beispiele für komplette Homeautomation Projekte unter Verwendung von jum:templates basierten Sensoren und anderen gängigen Homeautomation Systemen. Alle beschriebenen Projekte basieren auf der freien Homeautomation-Platform OpenHAB.

= jum:templates

Hier folgt die Beschreibung von jum:templates

= jum:projects

Hier folgt die Beschreibung von jum:projects
